### ISSUE TITLE
how to use this extension in browser?

### ISSUE THREAD

**Issue by softboy99** [MikeMcl/decimal.js-extensions#1]
this cannot be used in browser directly? Is it possible to merge it to decimal.js?

**Comment by MikeMcl** [comment]
An example of how to use the [evaluate](https://github.com/MikeMcl/decimal.js-extensions/tree/master/evaluate) extension in a browser: 

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>decimal.js-extension-evaluate</title>
<style>h1 {padding: 40vh 0;text-align: center}</style>
</head>
<body>
<h1></h1>
<script type="module">

  import Decimal from 'https://cdn.jsdelivr.net/npm/decimal.js@10.2.0/decimal.mjs';
  import { evaluate } from 'https://cdn.jsdelivr.net/npm/decimal.js-extensions-evaluate@0.1.0/index.min.js';

  evaluate.extend(Decimal);
  
  const expression = '2x + 4096y';
  const scope = { x: 3, y: '0.000244140625' };
  const result = Decimal.eval(expression, scope);
  
  document.querySelector('h1').textContent = `${expression} = ${result}`;

</script>
</body>
</html>
```

> Is it possible to merge it to decimal.js?

It would be easy to merge in, yes.

**Comment by softboy99** [comment]
Hi,
Sorry for the confusion,i'm using it in a chrome extension. How to do that in a chrome extension?

**Comment by MikeMcl** [comment]
This isn't an *issue*, it's a question. 
I don't know anything about chrome extensions, try [stackoverflow](https://stackoverflow.com/).
